# Remap leader from 'C-b' to 'C-s'
set -g prefix2 C-s
# renumber windows sequentially after closing any of them
set -g renumber-windows on

# usability improvements
set -sg escape-time 0
set -g set-clipboard on
set -g mouse on
# set-option -g status-position top

# ==========================================
# PLUGINS
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_date_time_text " %b %d"
set -g status-right-length 100
set -g status-left-length 100
set -ogq @catppuccin_window_text " #W"
set -ogq @catppuccin_window_current_text " #W"
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

run '~/.tmux/plugins/tpm/tpm'

# Override status bar background for transparency (must be after plugin load)
set -g status-bg default
set -g status-style bg=default
