[tools]
aube = "latest"
jq = "latest"
lua = "latest"
node = "latest"
"npm:typescript" = "latest"
opencode = "latest"
pi = "latest"
ruby = "latest"

[env]
HK_MISE = 1

[settings]
minimum_release_age = "0s"
