[tools]
aube = "latest"
deno = "latest"
lua = "latest"
node = "latest"
odin = "latest"
postgres = "latest"
ruby = "latest"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
compile = false
