# Extra Git abbreviations (common ones not yet in your config)
abbr -a ga "git add"
abbr -a gaa "git add --all"
abbr -a gap "git add --patch"
abbr -a gb "git branch"
abbr -a gba "git branch --all"
abbr -a gbd "git branch -d"
abbr -a gbm "git branch -m"
abbr -a gc "git commit"
abbr -a gca "git commit --amend"
abbr -a gcam "git commit --amend -m"
abbr -a gcm "git commit -m"
abbr -a gco "git checkout"
abbr -a gcob "git checkout -b"
abbr -a gcom "git switch main"
abbr -a gcp "git cherry-pick"
abbr -a gd "git diff"
abbr -a gds "git diff --staged"
abbr -a gf "git fetch"
abbr -a gfa "git fetch --all"
abbr -a gfu "git fetch upstream"
abbr -a gl "git log --oneline --graph"
abbr -a gla "git log --oneline --graph --all"
abbr -a glg "git log --all --decorate --oneline --graph"
abbr -a gm "git merge"
abbr -a gpl "git pull"
abbr -a gplo "git pull origin"
abbr -a gpo "git pull origin"
abbr -a gp "git push"
abbr -a gpf "git push --force-with-lease"
abbr -a gpr "gh pr create --fill"
abbr -a gpv "gh pr view --web"
abbr -a grb "git rebase"
abbr -a grbi "git rebase -i"
abbr -a grh "git reset HEAD"
abbr -a grs "git restore --staged"
abbr -a gs "git status"
abbr -a gss "git status --short"
abbr -a gsh "git show"
abbr -a gst "git stash"
abbr -a gsta "git stash apply"
abbr -a gstd "git stash drop"
abbr -a gstl "git stash list"
abbr -a gstp "git stash pop"
abbr -a gsw "git switch"
abbr -a gswc "git switch -c"
