abbr -a d docker
abbr -a dc "docker compose"
abbr -a dcu "docker compose up -d"
abbr -a dcd "docker compose down"
abbr -a dcl "docker compose logs -f"
abbr -a dcr "docker compose run --rm web"
abbr -a dce "docker compose exec web"
abbr -a dbuild "docker compose build"
abbr -a dps "docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'"
abbr -a dimg "docker images"
abbr -a dprune "docker system prune"
